### ISSUE TITLE
f-string syntax fails with Python 3.5

### ISSUE THREAD

**Issue by leungi** [songlab-cal/tape#1]
Thanks for the interesting pkg, and looking FW to try it!

On import, got the following:

```python
>>> from tape import ProteinBertModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\tape\__init__.py", line 1, in <module>
    from . import datasets  # noqa: F401
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\tape\datasets.py", line 31
    raise ValueError(f"Unrecognized datafile type {data_file.suffix}")
                                                                    ^
SyntaxError: invalid syntax
>>> from tape import TAPETokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\tape\__init__.py", line 1, in <module>
    from . import datasets  # noqa: F401
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\tape\datasets.py", line 31
    raise ValueError(f"Unrecognized datafile type {data_file.suffix}")
                                                                    ^
SyntaxError: invalid syntax
```

__System info__
```
{'commit_hash': '2eec187d3',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'D:\\Continuum\\anaconda3\\envs\\tape_proteins\\lib\\site-packages\\IPython',
 'ipython_version': '7.9.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.17134-SP0',
 'sys_executable': 'D:\\Continuum\\anaconda3\\envs\\tape_proteins\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.5.5 | packaged by conda-forge | (default, Jul 24 2018, '
                '01:52:17) [MSC v.1900 64 bit (AMD64)]'}
```

**Comment by rmrao** [comment]
Thanks for the interest! Looks like you're using python 3.5, so the f-string syntax isn't supported. I think to fix this, all f-strings need to be converted into regular format strings... which would take a bit since I think there are quite a few throughout this repository. So I think your options are

1. Use Python 3.6+
2. Submit a pull-request to change all f-strings to format strings
3. Wait until I eventually get around to fixing this, but it might take a bit

**Comment by leungi** [comment]
Noted; thanks @rmrao.

Updated to Python 3.6, and ran into another issue - unable to find `TAPETokenizer`.

```python
Python 3.6.7 (default, Dec  6 2019, 07:03:06) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tape import TAPETokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TAPETokenizer'
```

**Comment by rmrao** [comment]
Ah this is a mistake on my part - I thought I had pushed this change and I guess I didn't. Fixed this in #5. Will update the pip version in a bit. LMK if this fixes the issue.

**Comment by leungi** [comment]
Pulling from `commit b8cac73989f3e1e087d0117b1feeb244a642f0bb` solves it.

However, there seems to be a problem with model download; I don't see an argument to force re-download?

```python
Python 3.6.7 (default, Dec  6 2019, 07:03:06) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from tape import ProteinBertModel, TAPETokenizer
>>> model = ProteinBertModel.from_pretrained('bert-base')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\tape\models\modeling_utils.py", line 508, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\torch\serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Continuum\anaconda3\envs\tape_proteins\lib\site-packages\torch\serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2436457 more bytes. The file might be corrupted.
```

**Comment by rmrao** [comment]
Hmm. I haven't added a force re-download param, although it looks like huggingface has one. Can you try deleting the file at `~/.cache/torch/protein_models` and re-running? If that doesn't work it may be a consistent download issue.

**Comment by rmrao** [comment]
I just did the download on a new machine and it looks to have worked. So I'm guessing that this download just got corrupted. I'll create a new issue (see #6) about adding a force re-download. In the meantime, deleting the cache file and re-running should work.

**Comment by leungi** [comment]
Noted.

I'm using Windows but can't find the `protein_models` folder in `C:\Users\leungi\AppData\Local\pip\cache`; is there another location to look for?

**Comment by rmrao** [comment]
The code for finding the cache is

```python
try:
    from torch.hub import _get_torch_home
    torch_cache_home = _get_torch_home()
except ImportError:
    torch_cache_home = os.path.expanduser(
        os.getenv('TORCH_HOME', os.path.join(
            os.getenv('XDG_CACHE_HOME', '~/.cache'), 'torch')))
default_cache_path = os.path.join(torch_cache_home, 'protein_models')
```

**Comment by leungi** [comment]
Found it; deleting solves it.

Thanks again!
