### ISSUE TITLE
Assertion Error in Tape-Embed

### ISSUE THREAD

**Issue by sabyUWO** [songlab-cal/tape#30]
I am getting an error on tape-embed using a GPU. I am using batch size as 4 because of anything more causes memory issues in GPU. Please advise.

/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [256,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/bin/tape-embed", line 8, in <module>
    sys.exit(run_embed())
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/main.py", line 234, in run_embed
    training.run_embed(**embed_args)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/training.py", line 642, in run_embed
    outputs = runner.forward(batch, no_loss=True)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/training.py", line 86, in forward
    outputs = self.model(**batch)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/models/modeling_bert.py", line 449, in forward
    chunks=None)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/models/modeling_bert.py", line 346, in forward
    layer_outputs = layer_module(hidden_states, attention_mask)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/models/modeling_bert.py", line 285, in forward
    attention_outputs = self.attention(hidden_states, attention_mask)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/models/modeling_bert.py", line 242, in forward
    self_outputs = self.self(input_tensor, attention_mask)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/6000341/saby2k13/pyDPPI/kit/medver/lib/python3.6/site-packages/tape/models/modeling_bert.py", line 180, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA error: device-side assert triggered

**Comment by sabyUWO** [comment]
The human proteome passed as input for embedding: http://www.rostlab.org/~hampt/ppichallenges/human.fasta

**Comment by rmrao** [comment]
So it looks like you're trying to embed some *really* long proteins (looks like max length is 34350). This has a couple issues.

1. Because I just used a standard BERT implementation, the position encoding is learned, which creates a finite limit on how long a sequence can passed in. The limit for the `bert-base` model is 8096.
2. Even if this wasn't the case, I don't think a standard transformer would even be able to fit a sequence of length 34k in memory. Plausibly you would need a Transformer XL style model.
3. Finally, even in this case, there is limited evidence that networks actually are able to use that much input in any sort of reasonable manner. Even the Transformer XL will likely end up 'forgetting' the beginning of the input.

Overall, my suggestion would be to remove long sequences or cut them into smaller pieces. Average protein length in the training set was around 300 amino acids. The model will likely perform reasonably for proteins of length up to 1000. Beyond that, there is relatively little training data for proteins of length >1000, so I can't be sure how the model will perform. And finally, you will definitely experience a failure (that's what the assertion error is, torch is weird) if the length is > 8096.

**Comment by rmrao** [comment]
I'm going to close this, since I don't think it's an actual bug in our code. If you continue to have issues, feel free to reopen.
