### ISSUE TITLE
trRosetta problem with tape_embed

### ISSUE THREAD

**Issue by serbulent** [songlab-cal/tape#45]
Hello,

I'm trying to get embeddings with trRosetta as;

`tape-embed trrosetta my_fasta_file.fasta my_outout.npz xaa`

But getting error as below. I install tape first from pip repo then from github but the error persists.

Traceback (most recent call last):
File "/truba/home/sunsal/Apps/anaconda3/envs/tape_new/bin/tape-embed", line 8, in <module>
    sys.exit(run_embed())
  File "/truba/home/sunsal/Apps/anaconda3/envs/tape_new/lib/python3.7/site-packages/tape/main.py", line 234, in run_embed
    training.run_embed(**embed_args)
  File "/truba/home/sunsal/Apps/anaconda3/envs/tape_new/lib/python3.7/site-packages/tape/training.py", line 629, in run_embed
    model_type, task_spec.name, model_config_file, from_pretrained)
  File "/truba/home/sunsal/Apps/anaconda3/envs/tape_new/lib/python3.7/site-packages/tape/registry.py", line 214, in get_task_model
    model_cls = task_spec.get_model(model_name)
  File "/truba/home/sunsal/Apps/anaconda3/envs/tape_new/lib/python3.7/site-packages/tape/registry.py", line 44, in get_model
    return self.models[model_name]
KeyError: 'trrosetta'

**Comment by rmrao** [comment]
I have trrosetta implemented if you want to use it in your own scripts for structure prediction but it isn't available for embedding (I'm not sure what a TRRosetta embedding of a protein would produce, and it's not clear to me the best way of extracting an embedding from TRRosetta).

Additionally, I haven't updated the pip version in a while (it's on my TODO list), so you'll have to download from github if you want it.

**Comment by serbulent** [comment]
Thanks. A warning in readme might be useful for this.
