### ISSUE TITLE
CUDA oom with batch size 1

### ISSUE THREAD

**Issue by jxmorris12** [songlab-cal/tape#55]
I ran this command (with NVIDIA Apex installed):
```
tape-train-distributed transformer masked_language_modeling --nproc_per_node 4 --batch_size 1024 --grad
ient_accumulation_steps 256
```

and got the following output:
```
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 2; 7.43 GiB total capacity; 6.81 GiB already allocated; 6.94 MiB free; 6.94 GiB r
eserved in total by PyTorch)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/distributed_utils.py", line 38, in _wrap
    fn(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/main.py", line 191, in run_train
    training.run_train(**train_args)
  File "/opt/conda/lib/python3.7/site-packages/tape/training.py", line 536, in run_train
    break
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/utils.py", line 244, in __exit__
    raise RuntimeError(message)
RuntimeError: CUDA out of memory. Reduce batch size or increase gradient_accumulation_steps to divide each batch over more forward passes.
        Hyperparameters:
                batch_size per backward-pass: 1024
                gradient_accumulation_steps: 256
                n_gpu: 4
                batch_size per (gpu * forward-pass): 1
```

I got the same output with `tape-train` as with `tape-train-distributed`. I'm running on a machine with 4 GPUs. How can I be running out of memory if the batch size is (per gpu, per forward pass) is 1?  What can I do to actually run the training code on my machine?

**Comment by rmrao** [comment]
I'm not sure how the error you report is possible given the command you listed (batch size 1024, 4 nodes, and 512 gradient accumulation steps gives you a batch size of 0.5 per GPU).

Regardless, if you can't run a batch size of 1, here are my suggestions in order of difficulty:

1. Try running with the `--fp16` flag to use half precision, which should halve your memory footprint.
2. Train a smaller model.
3. Filter out the longest sequences from the dataset.
4. Play around with [gradient checkpointing](https://pytorch.org/docs/stable/checkpoint.html) inside the transformer encoder. Some of this code is actually already implemented but is not enabled. Anyway, this can also be useful for increasing the batch size.
5. Use a larger GPU :)

Hope that helps.

**Comment by jxmorris12** [comment]
I meant to write `gradient_accumulation_steps=256` (which is clearly printed in the output). I'll try these things and get back to you, thanks.

**Comment by jxmorris12** [comment]
Hi again @rmrao:

I successfully ran this for a decent amount of time before running out of memory again:

```
20/05/15 11:44:10 - INFO - tape.training -   [Ep: 0.84][Iter: 26680][Time: 278.81s][Loss: 2.2635][Perplexity: 10.734][LR: 9.459e-05]
Traceback (most recent call last):
  File "/opt/conda/bin/tape-train-distributed", line 8, in <module>
    sys.exit(run_train_distributed())
  File "/opt/conda/lib/python3.7/site-packages/tape/main.py", line 252, in run_train_distributed
    args.node_rank, args.master_addr, args.master_port)
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/distributed_utils.py", line 169, in launch_process_group
    while not process_context.join():
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/distributed_utils.py", line 122, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tape/training.py", line 508, in run_train
    viz, num_log_iter, gradient_accumulation_steps)
  File "/opt/conda/lib/python3.7/site-packages/tape/training.py", line 299, in run_train_epoch
    loss, metrics = runner.forward(batch)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/tape/training.py", line 85, in forward
    outputs = self.model(**batch)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 484, in forward
    outputs = self.bert(input_ids, input_mask=input_mask)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 449, in forward
    chunks=None)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 346, in forward
    layer_outputs = layer_module(hidden_states, attention_mask)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 285, in forward
    attention_outputs = self.attention(hidden_states, attention_mask)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 242, in forward
    self_outputs = self.self(input_tensor, attention_mask)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/models/modeling_bert.py", line 180, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 1; 7.43 GiB total capacity; 6.73 GiB already allocated; 84.94 MiB free; 6.86 GiB reserved in total by PyTorch)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/distributed_utils.py", line 38, in _wrap
    fn(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tape/main.py", line 191, in run_train
    training.run_train(**train_args)
  File "/opt/conda/lib/python3.7/site-packages/tape/training.py", line 536, in run_train
    break
  File "/opt/conda/lib/python3.7/site-packages/tape/utils/utils.py", line 244, in __exit__
    raise RuntimeError(message)
RuntimeError: CUDA out of memory. Reduce batch size or increase gradient_accumulation_steps to divide each batch over more forward passes.

        Hyperparameters:
                batch_size per backward-pass: 1024
                gradient_accumulation_steps: 256
                n_gpu: 4
                batch_size per (gpu * forward-pass): 1
``` 

![tape](https://user-images.githubusercontent.com/13238952/82071244-d2e0b980-96a3-11ea-8459-a5a682935ad4.png)

Additionally, here's an image of the perplexity during training. The reported perplexity (as ECE) in the paper was 6.01. Should I expect my model to reach a perplexity of 6.01, or is some configuration different? Although the perplexity was still slightly decreasing when I received the out-of-memory error, its minimum was 10.7; it did not seem to be approaching 6.01.

**Comment by rmrao** [comment]
It looks like you were using a learning rate of 1e-4. That’s set as default in TAPE because we use that for downstream tasks. For training the language model, we used a learning rate of 1e-3.

Additionally, we saw continuous decrease in loss over the course of all 10 epochs of training, so you should expect to see it continue to decrease.

**Comment by jxmorris12** [comment]
Thanks! I'll re-run and let you know how it goes.
