### ISSUE TITLE
tape-embed fails with more than 100k sequences in fasta file

### ISSUE THREAD

**Issue by sanjitsbatra** [songlab-cal/tape#7]
tape-embed works well with 1000 sequences but produces the following error with fasta files containing a large number of sequences (>~10k):
  0%|          | 0/49 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/bin/tape-embed", line 8, in <module>
    sys.exit(run_embed())
  File "/lib/python3.6/site-packages/tape/main.py", line 232, in run_embed
    training.run_embed(**embed_args)
  File "/lib/python3.6/site-packages/tape/training.py", line 637, in run_embed
    for batch in tqdm(valid_loader, total=len(valid_loader)):
  File "/lib/python3.6/site-packages/tqdm/std.py", line 1102, in __iter__
    for obj in iterable:
  File "/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/lib/python3.6/site-packages/tape/datasets.py", line 211, in __getitem__
    item = self.data[index]
  File "/lib/python3.6/site-packages/tape/datasets.py", line 95, in __getitem__
    record = self._records[key]
  File "/lib/python3.6/site-packages/Bio/File.py", line 430, in __getitem__
    raise ValueError("Key did not match (%s vs %s)" % (key, key2))
ValueError: Key did not match (bsnpaso1144 vs bsnph4874)
 
  0%|          | 0/49 [00:11<?, ?it/s]

**Comment by rmrao** [comment]
My guess is that somehow either I messed up with using `SeqIO.index` or that `SeqIO` has a bug. Out of curiosity, what are the largest fasta files you typically deal with (in bytes).

The easy solution to this is to read the whole file into memory, but if you're regularly dealing with 20GB fasta files maybe I'll think of something smarter 😄

**Comment by rmrao** [comment]
Hi Sanjit - I think that this should be fixed by #17. If that is not true, let me know.

**Comment by sanjitsbatra** [comment]
This seems to be fixed in the latest version. Thanks Roshan!
